name: Generate Directory Structure

on:
  push:
    branches:
      - main  # Adjust if your default branch is not 'main'

jobs:
  generate-directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the latest Node.js LTS version

      - name: Install dependencies
        run: npm install

      - name: Generate directory structure
        run: npm run generate

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add directory-structure.json
          git commit -m "Update directory structure"
          git push
